### ISSUE TITLE
Pinokio app stucks

### ISSUE THREAD

**Issue by ManakhovN** [pinokiofactory/photomaker2#1]
When I install it via discovery tab in Pinokio, the app just freezes. If I close it and open again, the ponokio app becomes blank. Removing folder photomaker2.git makes it work again
![image](https://github.com/user-attachments/assets/886a499b-0044-438b-a8f5-650f214d8260)

**Comment by 6Morpheus6** [comment]
> When I install it via discovery tab in Pinokio, the app just freezes. If I close it and open again, the ponokio app becomes blank. Removing folder photomaker2.git makes it work again

@ManakhovN 
Please download and install the latest version of Pinokio for your OS from here. [pinokio.computer](https://program.pinokio.computer/#/?id=install)
Photomaker2 is working. But it needs the latest version of Pinokio to get installed properly.

**Comment by ManakhovN** [comment]
Hi, I've updated Pinokio, and It kinda helped. Now it is stuck on solving the environment and then writes "failed" after a while.
![image](https://github.com/user-attachments/assets/5fe2827e-8fa7-45b8-ab71-2b917994a80b)

**Comment by ManakhovN** [comment]
Ok, Sorry. I just had to wait more and it got installed

**Comment by 6Morpheus6** [comment]
> Hi, I've updated Pinokio, and It kinda helped. Now it is stuck on solving the environment and then writes "failed" after a while. ![image](https://private-user-images.githubusercontent.com/7031314/352668607-5fe2827e-8fa7-45b8-ab71-2b917994a80b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzNzY5MzUsIm5iZiI6MTcyMjM3NjYzNSwicGF0aCI6Ii83MDMxMzE0LzM1MjY2ODYwNy01ZmUyODI3ZS04ZmE3LTQ1YjgtYWI3MS0yYjkxNzk5NGE4MGIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDczMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MzBUMjE1NzE1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWFiZTFmYTRjZWVkOTg5YmI3ZTk4YjhhYWVhYjc3MzY4YTlhNTBjY2U3Y2M5YWMyMDYxNzgwODI1ODUzZTM3ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.W0_7zUntsGc7bIb3CjcqmEuVuryzVWr9v15uk3b2hDE)

For everyone who struggles with the environment getting solved in Photomaker 2 (being stuck or failure)
The solution is to reset Photomaker 2 and delete `.\pinokio\bin`
The environment will be recreated and can be solved afterwards.
